### ISSUE TITLE
qq的用户信息没有返回id，QQ空间分享不能用，给人感觉一堆问题

### ISSUE THREAD

**Issue by 3067200952** [MobClub/ShareSDK-For-Flutter#16]

**Comment by DangerousDON** [comment]
这边说的是安卓的还是ios的呢？



刘芳丽
MOB云事业部 技术支持 
YOOZOO GAMES 游族网络

E • liufl@yoozoo.com
M • +86 18824179331
T • +86 21 3367 6512
F • +86 21 3367 6520

YOOZOO MANSION,BUILDING 2,711 YISHAN RD.,XUHUI DISTRICT,SHANGHAI,CHINA 上海市徐汇区宜山路711号2号楼游族大厦 2200233




本邮件可能载有机密内容，非指定收件人请勿打开、复制本邮件或依赖本邮件的内容而采取任何行动。若误收到本邮件，请立即通知发送人，并删除本邮件及其附件。谢谢！
This message contains information which may be confidential and privileged. If you received the message by mistake, please inform the sender and delete the message as soon as possible, thanks.

 
发件人： Wow_Wow
发送时间： 2019-04-30 09:48
收件人： MobClub/ShareSDK-For-Flutter
抄送： Subscribed
主题： [MobClub/ShareSDK-For-Flutter] qq的用户信息没有返回id，QQ空间分享不能用，给人感觉一堆问题 (#16)

**Comment by 3067200952** [comment]
安卓，ios不知道

**Comment by DangerousDON** [comment]
亲，这边我们测试QQ空间分享是正常的哦，您那边是用的什么方法测试的呢，您那边最好是加下我们的技术扣，4006852216，节后过来有我们的技术人员帮您看下



刘芳丽
MOB云事业部 技术支持 
YOOZOO GAMES 游族网络

E • liufl@yoozoo.com
M • +86 18824179331
T • +86 21 3367 6512
F • +86 21 3367 6520

YOOZOO MANSION,BUILDING 2,711 YISHAN RD.,XUHUI DISTRICT,SHANGHAI,CHINA 上海市徐汇区宜山路711号2号楼游族大厦 2200233




本邮件可能载有机密内容，非指定收件人请勿打开、复制本邮件或依赖本邮件的内容而采取任何行动。若误收到本邮件，请立即通知发送人，并删除本邮件及其附件。谢谢！
This message contains information which may be confidential and privileged. If you received the message by mistake, please inform the sender and delete the message as soon as possible, thanks.

 
发件人： Wow_Wow
发送时间： 2019-04-30 12:42
收件人： MobClub/ShareSDK-For-Flutter
抄送： Donel Chan; Comment
主题： Re: [MobClub/ShareSDK-For-Flutter] qq的用户信息没有返回id，QQ空间分享不能用，给人感觉一堆问题 (#16)
安卓，ios不知道

**Comment by 3067200952** [comment]
分享类型直接改成QQ空间然后就报错了

**Comment by StarAndRainbow** [comment]
同样，qq空间分享也报了个错，java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.sharesdk.framework.Platform.setPlatformActionListener(cn.sharesdk.framework.PlatformActionListener)' on a null object reference

**Comment by hu1095878620** [comment]
qq控件分享报错：
E/MethodChannel#com.yoozoo.mob/sharesdk: Failed to handle method call
    java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.sharesdk.framework.Platform.setPlatformActionListener(cn.sharesdk.framework.PlatformActionListener)' on a null object reference
        at com.yoozoo.sharesdk.SharesdkPlugin.shareWithArgs(SharesdkPlugin.java:273)
        at com.yoozoo.sharesdk.SharesdkPlugin.onMethodCall(SharesdkPlugin.java:63)，

解决了希望说一声

**Comment by hlj2722** [comment]
QQ空间分享中， image url 包含中文时，有些包含中文的图片链接会无法生成缩图，有些又可以

**Comment by moblarry** [comment]
> QQ空间分享中，image url包含中文时，有些包含中文的图片链接会无法生成缩图，有些又可以

我们不对链接进行处理的，是直接传到QQ的接口的，如果可以的话您可以将链接发我下，我拿原生的测试下，看看是否可以，或者您自己下载到本地分享本地图片，就是多了一层的步骤比较麻烦些

**Comment by uddsoft** [comment]
我也遇到了。按照demo请求微信分享接口。
`E/MethodChannel#com.yoozoo.mob/sharesdk(12932): Failed to handle method call
E/MethodChannel#com.yoozoo.mob/sharesdk(12932): java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.sharesdk.framework.Platform.setPlatformActionListener(cn.sharesdk.framework.PlatformActionListener)' on a null object reference
E/MethodChannel#com.yoozoo.mob/sharesdk(12932): 	at com.yoozoo.sharesdk.SharesdkPlugin.shareWithArgs(SharesdkPlugin.java:385)
E/MethodChannel#com.yoozoo.mob/sharesdk(12932): 	at com.yoozoo.sharesdk.SharesdkPlugin.onMethodCall(SharesdkPlugin.java:134)
E/MethodChannel#com.yoozoo.mob/sharesdk(12932): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#com.yoozoo.mob/sharesdk(12932): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#com.yoozoo.mob/sharesdk(12932): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#com.yoozoo.mob/sharesdk(12932): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#com.yoozoo.mob/sharesdk(12932): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#com.yoozoo.mob/sharesdk(12932): 	at android.os.Looper.loop(Looper.java:135)
E/MethodChannel#com.yoozoo.mob/sharesdk(12932): 	at android.app.ActivityThread.main(ActivityThread.java:7224)
E/MethodChannel#com.yoozoo.mob/sharesdk(12932): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.yoozoo.mob/sharesdk(12932): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/MethodChannel#com.yoozoo.mob/sharesdk(12932): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by slimcheng** [comment]
我把解决方案发一下，也是搜了一圈没有答案，最后联系的客服。

出现这个问题是因为 ‘build.gradle’ 中对应平台的配置信息没有加上

可能也是因为官方文档说的不清楚

我这边是 qq空间和微信朋友圈报错：分别对应的配置项是：WechatMoments、Qzone，里面的属性和Wechat、QQ保持一致即可。

如下：
```
MobSDK {
    appKey "2ed2e7699e9d4"
    appSecret "796caf0b2c00a4fb76184ffa94204dfb"

    ShareSDK {
        //平台配置信息
        devInfo {
            Wechat {
                appId "wxe1111111111"
                appSecret "e111111111111111111111111dabd"
            }
            WechatMoments {
                appId "wxe1111111111"
                appSecret "e111111111111111111111111dabd"
            }

            QQ {
                appId "100000005"
                appKey "e111111111111111111111111111111111e"
                shareByAppClient true
            }
            Qzone {
                appId "100000005"
                appKey "e111111111111111111111111111111111e"
            }
        }
    }
}
```
