### ISSUE TITLE
MissingPluginException(No implementation found for method listen on channel JAVA_TO_FLUTTER)

### ISSUE THREAD

**Issue by jasper2007111** [MobClub/ShareSDK-For-Flutter#17]
会报如下错误：

flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following MissingPluginException was thrown while activating platform stream on channel
flutter: JAVA_TO_FLUTTER:
flutter: MissingPluginException(No implementation found for method listen on channel JAVA_TO_FLUTTER)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
flutter: <asynchronous suspension>
flutter: #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:490:29)
flutter: <asynchronous suspension>
flutter: #6      ShareSDK.listenNativeEvent (package:sharesdk/sharesdk_interface.dart:16:10)

**Comment by moblarry** [comment]
> 会报如下错误：

有具体接口吗？或者具体实现什么方法报错？

**Comment by songshitong** [comment]
应该是example在initState中调用了ShareSDK.listenNativeEvent()，这应该是Android才有的方法，运行在iOS会报错，加个判断就能正常运行了
```
if (TargetPlatform.android == defaultTargetPlatform) {
      ShareSDK.listenNativeEvent();
    }
```
