### ISSUE TITLE
小米手机：分享失败，也没有分享回调

### ISSUE THREAD

**Issue by jicg** [MobClub/ShareSDK-For-Flutter#42]
```dart
 SharesdkPlugin.showMenu(
                                null,
                                    SSDKMap()
                                      ..setGeneral(
                                          "首页分享",
                                          "",
                                          //images
                                          [],
                                          //imageUrlAndroid
                                          null,
                                          //imagePathAndroid
                                          null,
                                          //url
                                          "https://baidu.com",
                                          //titleUrlAndroid
                                         null,
                                          //musicUrlAndroid
                                          null,
                                          //videoUrlAndroid
                                          null,
                                          SSDKContentTypes.webpage),
                                    (SSDKResponseState state,
                                        ShareSDKPlatform p,
                                        Map data,
                                        Map user,
                                        SSDKError err) {
                                  print(
                                      "showMenu --> $state $p $data $user $err");
                                });
```

```log
W/System.err:System.err: java.lang.Throwable: sendReq checkArgs fail
W/System.err:     at cn.sharesdk.wechat.utils.i.a(WechatCore.java:60)
W/System.err:     at cn.sharesdk.wechat.utils.k.a(WechatHelper.java:752)
W/System.err:     at cn.sharesdk.wechat.utils.k.a(WechatHelper.java:301)
W/System.err:     at cn.sharesdk.wechat.utils.k.b(WechatHelper.java:115)
W/System.err:     at cn.sharesdk.wechat.friends.Wechat.doShare(Wechat.java:248)
W/System.err:     at cn.sharesdk.framework.f.b(PlatformImpl.java:282)
W/System.err:     at cn.sharesdk.framework.f$4.run(PlatformImpl.java:353)
```
小米手机
flutter doctor
```
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.17134.1069], locale zh-CN)
    • Flutter version 1.9.1+hotfix.4 at D:\App\flutter
    • Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:/App/AndroidSdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = D:/App/AndroidSdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.5)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8580
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (2 available)
    • MI PLAY                   • 49e7b9d20301  • android-arm64 • Android 8.1.0 (API 27)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

**Comment by jicg** [comment]
目前测试，单独分享客户回调。弹出菜单后的分享是没有回调！

**Comment by jicg** [comment]
微信的分享是wechatTimeline，不知道 wechatSeries是什么。。。
