### ISSUE TITLE
升级到最新版，迁移到AndroidX，打包后登录不了，分享不了

### ISSUE THREAD

**Issue by MrWangYc** [MobClub/ShareSDK-For-Flutter#52]
微信登录报错 SharesdkPlugin:  platName null ====> {platform=22}

分享报错  2019-12-31 17:17:23.442 8575-8575/? E/MethodChannel#com.yoozoo.mob/sharesdk: Failed to handle method call
    java.lang.NullPointerException: Attempt to invoke virtual method 'void c.b.a.b.a(c.b.a.c)' on a null object reference
        at d.f.a.a.h(Unknown Source:1042)
        at d.f.a.a.onMethodCall(Unknown Source:180)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(Unknown Source:57)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-12-31 17:17:23.443 8575-8616/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'void c.b.a.b.a(c.b.a.c)' on a null object reference, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569)
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316)
    <asynchronous suspension>
    #2      SharesdkPlugin.share (package:sharesdk_plugin/sharesdk_interface.dart:48)
    #3      DetailsActionsShare.shareToWechat (package:rong_c/pages/house/details_share/details_actions_share.dart:237)
    #4      DetailsActionsShare._creatRow.<anonymous closure> (package:rong_c/pages/house/details_share/details_actions_share.dart:157)
    #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654)
    #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729)
    #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182)
    #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365)
    #9      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312)
    #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156)
    #11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222)
    #12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198)
    #13     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156)
    #14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102)
    #15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86)
    #16     _rootRunUnary (dart:async/zone.dart:1136)
    #17     _CustomZone.runUnary (dart:async/zone.dart:1029)
    #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931)
    #19     _invoke1 (dart:ui/hooks.dart:263)
    #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:172)

**Comment by MuZiLee** [comment]
同样问题,升级后iOS分享不了

**Comment by mickyliu945** [comment]
same error

**Comment by c1s1x1** [comment]
same error,Can it be fixed?

**Comment by lywh1987** [comment]
same error

**Comment by lywh1987** [comment]
same error，how to fix it?

**Comment by lywh1987** [comment]
fixed,settings.gradle just modify like demo.
