### ISSUE TITLE
单独分享微信图片失败

### ISSUE THREAD

**Issue by xiang23** [MobClub/ShareSDK-For-Flutter#69]
SSDKMap()
                                    ..setGeneral(
                                        null,
                                        null,
                                        !Platform.isIOS
                                            ? null
                                            : model.imgFile.path ?? "",
                                        null,
                                        !Platform.isAndroid
                                            ? null
                                            : model.imgFile.path ?? "",
                                        null,
                                        null,
                                        null,
                                        null,
                                        null,
                                        SSDKContentTypes.image);

 SharesdkPlugin.share(platform, ssdkMap, (state, t1, t2, error) {
      if (error != null && mounted) {
        showToast(S.of(context).shareFail, context: context);
      }
    });

`E/MethodChannel#com.yoozoo.mob/sharesdk(23439): Failed to handle method call
E/MethodChannel#com.yoozoo.mob/sharesdk(23439): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
E/MethodChannel#com.yoozoo.mob/sharesdk(23439): 	at com.yoozoo.sharesdk.SharesdkPlugin.shareWithArgs(SharesdkPlugin.java:416)
E/MethodChannel#com.yoozoo.mob/sharesdk(23439): 	at com.yoozoo.sharesdk.SharesdkPlugin.onMethodCall(SharesdkPlugin.java:162)
E/MethodChannel#com.yoozoo.mob/sharesdk(23439): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#com.yoozoo.mob/sharesdk(23439): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#com.yoozoo.mob/sharesdk(23439): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#com.yoozoo.mob/sharesdk(23439): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#com.yoozoo.mob/sharesdk(23439): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#com.yoozoo.mob/sharesdk(23439): 	at android.os.Looper.loop(Looper.java:197)
E/MethodChannel#com.yoozoo.mob/sharesdk(23439): 	at android.app.ActivityThread.main(ActivityThread.java:8016)
E/MethodChannel#com.yoozoo.mob/sharesdk(23439): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.yoozoo.mob/sharesdk(23439): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/MethodChannel#com.yoozoo.mob/sharesdk(23439): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
E/flutter (23439): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference, null)
E/flutter (23439): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (23439): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (23439): <asynchronous suspension>
E/flutter (23439): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (23439): #3      SharesdkPlugin.share (package:sharesdk_plugin/sharesdk_interface.dart:30:18)
E/flutter (23439): #4      _ShareAppPageState._doShare (package:labelplus/ui/my/share_app_page.dart:46:20)
E/flutter (23439): #5      _ShareAppPageState.build.<anonymous closure>.<anonymous closure> (package:labelplus/ui/my/share_app_page.dart:120:31)
E/flutter (23439): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (23439): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (23439): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (23439): #9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter (23439): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter (23439): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (23439): #12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (23439): #13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (23439): #14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (23439): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (23439): #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (23439): #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (23439): #18     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (23439): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (23439): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (23439): #21     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (23439): #22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (23439): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (23439): #24     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (23439): #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
E/flutter (23439): `

**Comment by ueed** [comment]
参数设置少了,
![image](https://user-images.githubusercontent.com/58243225/88387298-c0da7000-cde4-11ea-8e16-58366903fab9.png)不可以缺少参数
